// Generated by https://quicktype.io

export interface ITorrentResponse {
  items: ITorrent[];
  feedUrl: string;
  paginationLinks: IPaginationLinks;
  title: string;
  description: string;
  link: string;
}

interface IPaginationLinks {
  self: string;
}

export interface ITorrent {
  title: string;
  link: string;
  pubDate: string;
  seeders: string;
  leechers: string;
  size: string;
  category: string;
  content: string;
  contentSnippet: string;
  guid: string;
  isoDate: Date;
}
